-- Supabase ERP schema
-- Business rules:
-- - Inventory is measured in boxes.
-- - Products name is unique and required.
-- - Product stock cannot go negative.
-- - Sale customer_id is optional, but customer_name and customer_contact are always stored.
-- - Sale items are stored as JSONB in a single sales.items column.
-- - Sales inventory updates are atomic and validated before committing.

BEGIN;

-- Optional: enable extensions if needed
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    quantity_per_box INTEGER NOT NULL CHECK (quantity_per_box > 0),
    rate NUMERIC(18,2) NOT NULL CHECK (rate >= 0),
    mrp NUMERIC(18,2) NOT NULL CHECK (mrp >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Purchases table
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    rate NUMERIC(18,2) NOT NULL CHECK (rate >= 0),
    mrp NUMERIC(18,2) NOT NULL CHECK (mrp >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Customers table
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Purchase-triggered stock and rate update
CREATE OR REPLACE FUNCTION public.apply_purchase_to_product()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.products
    SET
        stock = stock + NEW.quantity,
        rate = NEW.rate,
        mrp = NEW.mrp,
        updated_at = NOW()
    WHERE id = NEW.product_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER apply_purchase_to_product
AFTER INSERT ON public.purchases
FOR EACH ROW
EXECUTE FUNCTION public.apply_purchase_to_product();

-- Sales table
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_contact TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::JSONB,
    total_amount NUMERIC(18,2) NOT NULL CHECK (total_amount >= 0),
    payment_status TEXT NOT NULL CHECK (payment_status IN ('Paid', 'Pending', 'Partial')),
    amount_paid NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
    balance_amount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (balance_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT sales_customer_details_required CHECK (
        TRIM(customer_name) <> '' AND TRIM(customer_contact) <> ''
    ),
    CONSTRAINT sales_items_are_json_array CHECK (
        jsonb_typeof(items) = 'array' AND jsonb_array_length(items) > 0
    ),
    CONSTRAINT sales_payment_rules CHECK (
        (
            payment_status = 'Paid'
            AND amount_paid = total_amount
            AND balance_amount = 0
        )
        OR (
            payment_status = 'Pending'
            AND amount_paid = 0
            AND balance_amount = total_amount
        )
        OR (
            payment_status = 'Partial'
            AND amount_paid > 0
            AND amount_paid < total_amount
            AND balance_amount = total_amount - amount_paid
        )
    )
);

-- Shared update timestamp trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_customers_updated_at
BEFORE UPDATE ON public.customers
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_products_name
    ON public.products (LOWER(name));

CREATE INDEX IF NOT EXISTS idx_purchases_product_id
    ON public.purchases (product_id);

CREATE INDEX IF NOT EXISTS idx_purchases_date
    ON public.purchases (date);

CREATE INDEX IF NOT EXISTS idx_customers_contact
    ON public.customers (contact);

CREATE INDEX IF NOT EXISTS idx_sales_customer_id
    ON public.sales (customer_id);

CREATE INDEX IF NOT EXISTS idx_sales_date
    ON public.sales (date);

CREATE INDEX IF NOT EXISTS idx_sales_items_gin
    ON public.sales USING GIN (items jsonb_path_ops);

-- Validate sale items JSON structure
CREATE OR REPLACE FUNCTION public.validate_sale_items(p_items JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT COALESCE(
        bool_and(
            jsonb_typeof(item) = 'object'
            AND (item ->> 'product_id') IS NOT NULL
            AND (item ->> 'product_id') ~ '^\\d+$'
            AND ((item ->> 'product_id')::BIGINT) > 0
            AND (item ->> 'quantity') IS NOT NULL
            AND (item ->> 'quantity') ~ '^\\d+$'
            AND ((item ->> 'quantity')::INTEGER) > 0
            AND (item ->> 'rate') IS NOT NULL
            AND (item ->> 'mrp') IS NOT NULL
            AND ((item ->> 'rate')::NUMERIC) >= 0
            AND ((item ->> 'mrp')::NUMERIC) >= 0
        ),
        FALSE
    )
    FROM jsonb_array_elements(p_items) AS item;
$$;

-- Optional business constraint to ensure each sale item object is valid
ALTER TABLE public.sales
    ADD CONSTRAINT sales_items_valid
    CHECK (
        jsonb_typeof(items) = 'array'
        AND jsonb_array_length(items) > 0
        AND validate_sale_items(items)
    );

-- Atomic sale creation with stock validation and stock deduction
CREATE OR REPLACE FUNCTION public.create_sale_transaction(
    p_date DATE,
    p_customer_id BIGINT,
    p_customer_name TEXT,
    p_customer_contact TEXT,
    p_items JSONB,
    p_total_amount NUMERIC(18,2),
    p_payment_status TEXT,
    p_amount_paid NUMERIC(18,2),
    p_balance_amount NUMERIC(18,2)
)
RETURNS public.sales
LANGUAGE plpgsql
AS $$
DECLARE
    v_sale_id BIGINT;
    v_item JSONB;
    v_product_id BIGINT;
    v_quantity INTEGER;
    v_current_stock INTEGER;
BEGIN
    IF p_customer_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.customers WHERE id = p_customer_id
    ) THEN
        RAISE EXCEPTION 'Customer not found for customer_id=%', p_customer_id;
    END IF;

    IF p_customer_name IS NULL OR TRIM(p_customer_name) = '' THEN
        RAISE EXCEPTION 'customer_name is required';
    END IF;

    IF p_customer_contact IS NULL OR TRIM(p_customer_contact) = '' THEN
        RAISE EXCEPTION 'customer_contact is required';
    END IF;

    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'sales.items must be a non-empty JSONB array';
    END IF;

    IF NOT public.validate_sale_items(p_items) THEN
        RAISE EXCEPTION 'Invalid sale item payload';
    END IF;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item ->> 'product_id')::BIGINT;
        v_quantity := (v_item ->> 'quantity')::INTEGER;

        SELECT stock
        INTO v_current_stock
        FROM public.products
        WHERE id = v_product_id
        FOR UPDATE;

        IF v_current_stock IS NULL THEN
            RAISE EXCEPTION 'Product with id % does not exist', v_product_id;
        END IF;

        IF v_current_stock < v_quantity THEN
            RAISE EXCEPTION 'Insufficient stock for product_id=%: available=% requested=%',
                v_product_id,
                v_current_stock,
                v_quantity;
        END IF;
    END LOOP;

    INSERT INTO public.sales (
        date,
        customer_id,
        customer_name,
        customer_contact,
        items,
        total_amount,
        payment_status,
        amount_paid,
        balance_amount
    )
    VALUES (
        p_date,
        p_customer_id,
        p_customer_name,
        p_customer_contact,
        p_items,
        p_total_amount,
        p_payment_status,
        p_amount_paid,
        p_balance_amount
    )
    RETURNING id INTO v_sale_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item ->> 'product_id')::BIGINT;
        v_quantity := (v_item ->> 'quantity')::INTEGER;

        UPDATE public.products
        SET stock = stock - v_quantity,
            updated_at = NOW()
        WHERE id = v_product_id;
    END LOOP;

    RETURN QUERY
    SELECT *
    FROM public.sales
    WHERE id = v_sale_id;
END;
$$;

-- RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- For Supabase apps using authentication:
-- Replace auth.uid() with a stricter app policy if needed.

CREATE POLICY "Authenticated users can view products"
ON public.products
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage products"
ON public.products
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can view purchases"
ON public.purchases
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage purchases"
ON public.purchases
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can view customers"
ON public.customers
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage customers"
ON public.customers
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can view sales"
ON public.sales
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage sales"
ON public.sales
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Notes:
-- If you are not using auth yet, change the above policies to public/anon as needed.
-- The create_sale_transaction RPC is the recommended way to safely update stock and sales together.

COMMIT;
